# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98a15043f7fa95f04a823d43896b4bfdc0397a25b37eba945da2e9fdf558a92332dbd6ae1405dc27750245d4fcdc7859d4eb1f9c48c4d887cbb6d870708d084

test:
  secret_key_base: b64d12fbb505b4be5d5bb3764a01c5bdbf3eb3e5771bf9644022073d24afe906737244e7d0d65bef18a6d2e27fed9cce7d50920bcf3f5b2b97664b53417c68ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
